### ISSUE TITLE
can't find release for rock64(RK3328)

### ISSUE THREAD

**Issue by silverchen0402** [mrfixit2001/recalbox-rockchip#1]
Thanks for your hard works for this, but I didn't find img for RK3328(rock64), is there anything wrong?

**Comment by mrfixit2001** [comment]
Thanks for asking! I am currently finishing up the rk3328 builds. There were a few additional tweaks necessary for best performance. Should be available soon.

**Comment by mrfixit2001** [comment]
RK3328 updates - rock64 and rockbox - have now been uploaded :) Enjoy!
