### ISSUE TITLE
ES crashing when USB plugged in

### ISSUE THREAD

**Issue by Nathan-j-hardee** [mrfixit2001/recalbox-rockchip#10]
this is on a ROCKPRO64, happens on clean install, can be replicated by wiping the SD, then re-imaging. 

image will boot with no errors, but once a USB device has been plugged in it will crash. if you leave the USB plugged in during boot it will never boot. USB Mouse/keyboard works, controllers do not. 

during this time the network is still live, full access to SSH. 

Image used:
recalbox-rockpro-mrfixit-200607

Previous version 200304 works until you go to configure the controller. 

messages logs when plugged in: 

Jul 17 21:58:43 RECALBOX user.info kernel: [  520.639219] usb 2-1: new full-speed USB device number 2 using ohci-platform
Jul 17 21:58:43 RECALBOX user.info kernel: [  520.938107] usb 2-1: New USB device found, idVendor=045e, idProduct=028e
Jul 17 21:58:43 RECALBOX user.info kernel: [  520.938124] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jul 17 21:58:43 RECALBOX user.info kernel: [  520.938132] usb 2-1: Product: 8BitDo Receiver
Jul 17 21:58:43 RECALBOX user.info kernel: [  520.938139] usb 2-1: Manufacturer: 8BitDo
Jul 17 21:58:43 RECALBOX user.info kernel: [  520.938177] usb 2-1: SerialNumber: Receiver     
Jul 17 21:58:43 RECALBOX user.info kernel: [  520.940819] input: Microsoft X-Box 360 pad as /devices/platform/fe3e0000.usb/usb2/2-1/2-1:1.0/input/input4
Jul 17 21:58:45 RECALBOX user.info kernel: [  522.503525] rockchip-vop ff900000.vop: [drm:vop_crtc_enable] Update mode to 1920x1080p60, type: 11
Jul 17 22:01:19 RECALBOX user.info kernel: [  676.988854] rockchip-vop ff900000.vop: [drm:vop_crtc_enable] Update mode to 1920x1080p60, type: 11

**Comment by Nathan-j-hardee** [comment]
ES gives this when starting:

[2020/07/18 01:22:54.448] (INFO ) : Settings instance created.
[2020/07/18 01:22:54.449] (ERROR) : Unknown field EnableSounds
[2020/07/18 01:22:54.449] (ERROR) : Unknown field RomsManager
[2020/07/18 01:22:54.449] (ERROR) : Unknown field INPUT P1
[2020/07/18 01:22:54.449] (ERROR) : Unknown field INPUT P2
[2020/07/18 01:22:54.449] (ERROR) : Unknown field INPUT P3
[2020/07/18 01:22:54.449] (ERROR) : Unknown field INPUT P4
[2020/07/18 01:22:54.449] (INFO ) : RecalboxConf instance created.
[2020/07/18 01:22:54.450] (INFO ) : NotificationManager instance created.
[2020/07/18 01:22:54.450] (INFO ) : EmulationStation - v dev, built Jun  7 2020 - 20:21:38
[2020/07/18 01:22:54.450] (WARN!) : Locale: /usr/bin/locale/lang/en_US/LC_MESSAGES/emulationstation2.mo not found.
[2020/07/18 01:22:54.450] (WARN!) : Locale: /usr/share/locale/en_US/LC_MESSAGES/emulationstation2.mo not found.
[2020/07/18 01:22:54.450] (WARN!) : Locale: /usr/bin/locale/lang/en_US/LC_MESSAGES/emulationstation2.mo not found.
[2020/07/18 01:22:54.451] (WARN!) : Locale: /usr/share/locale/en_US/LC_MESSAGES/emulationstation2.mo not found.
[2020/07/18 01:22:54.451] (WARN!) : No locale found. Default text used.
[2020/07/18 01:22:54.451] (ERROR) : [MQTT] Sending messageConnexion to tcp://127.0.0.1:1883 from recalbox-emulationstation failed (send) !
[2020/07/18 01:22:54.452] (INFO ) : Creating surface...
[2020/07/18 01:22:54.470] (INFO ) : Created window successfully.
[2020/07/18 01:22:54.687] (INFO ) : ViewController instance created.
[2020/07/18 01:22:54.828] (INFO ) : Checking available OpenGL extensions...
[2020/07/18 01:22:54.828] (INFO ) :  ARB_texture_non_power_of_two: MISSING
[2020/07/18 01:22:54.857] (ERROR) : Main thread crashed (outer).
[2020/07/18 01:22:54.857] (ERROR) : Exception: basic_string::_M_construct null not valid
[2020/07/18 01:22:54.857] (INFO ) : EmulationStation cleanly shutting down.
[2020/07/18 01:22:54.958] (INFO ) : Closing logger...

**Comment by eiddor** [comment]
I see this behavior when I connect my USB 8BitDo SN30 Pro, as well - I do not see it when I connect a Buffalo USB Gamepad.  ES appears to restart and then gets stuck at the recalbox splash screen (the one with the Pac-Man Ghosts).

Here's /var/log/messages when the 8BitDo controller is connected:

```
Jul 18 18:38:47 RECALBOX user.info kernel: [   79.692072] usb 7-1.2: new full-speed USB device number 4 using ehci-platform
Jul 18 18:38:48 RECALBOX user.info kernel: [   79.874353] usb 7-1.2: New USB device found, idVendor=045e, idProduct=028e
Jul 18 18:38:48 RECALBOX user.info kernel: [   79.874365] usb 7-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jul 18 18:38:48 RECALBOX user.info kernel: [   79.874370] usb 7-1.2: Product: Controller
Jul 18 18:38:48 RECALBOX user.info kernel: [   79.874375] usb 7-1.2: Manufacturer: Controller
Jul 18 18:38:48 RECALBOX user.info kernel: [   79.874379] usb 7-1.2: SerialNumber: Controller
Jul 18 18:38:48 RECALBOX user.info kernel: [   79.875247] input: Microsoft X-Box 360 pad as /devices/platform/fe380000.usb/usb7/7-1/7-1.2/7-1.2:1.0/input/input5
Jul 18 18:38:49 RECALBOX user.info kernel: [   81.330776] rockchip-vop ff900000.vop: [drm:vop_crtc_enable] Update mode to 1920x1080p60, type: 11
```

This is when the Buffalo gamepad is connected:

```
Jul 18 18:47:19 RECALBOX user.info kernel: [   49.733051] usb 7-1.4: new low-speed USB device number 3 using ehci-platform
Jul 18 18:47:20 RECALBOX user.info kernel: [   49.913011] usb 7-1.4: New USB device found, idVendor=0583, idProduct=2060
Jul 18 18:47:20 RECALBOX user.info kernel: [   49.913037] usb 7-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
Jul 18 18:47:20 RECALBOX user.info kernel: [   49.913042] usb 7-1.4: Product: USB,2-axis 8-button gamepad  
Jul 18 18:47:20 RECALBOX user.info kernel: [   49.917783] input: USB,2-axis 8-button gamepad   as /devices/platform/fe380000.usb/usb7/7-1/7-1.4/7-1.4:1.0/0003:0583:2060.0001/input/input4
Jul 18 18:47:20 RECALBOX user.info kernel: [   49.969569] hid-generic 0003:0583:2060.0001: input,hidraw0: USB HID v1.10 Joystick [USB,2-axis 8-button gamepad  ] on usb-fe380000.usb-1.4/input0
```

**Comment by Nathan-j-hardee** [comment]
im thinking its just anything that identifies as an Xbox 360 controller, xbox plugged in:

Jul 18 23:52:49 RECALBOX user.info kernel: [  113.639701] usb 8-1: USB disconnect, device number 2
Jul 18 23:52:49 RECALBOX user.err kernel: [  113.640232] xpad 8-1:1.0: xpad_try_sending_next_out_packet - usb_submit_urb failed with result -19
Jul 18 23:53:50 RECALBOX user.info kernel: [  174.437100] usb 5-1: new full-speed USB device number 2 using xhci-hcd
Jul 18 23:53:50 RECALBOX user.info kernel: [  174.664532] usb 5-1: New USB device found, idVendor=045e, idProduct=028e
Jul 18 23:53:50 RECALBOX user.info kernel: [  174.664550] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jul 18 23:53:50 RECALBOX user.info kernel: [  174.664558] usb 5-1: Product: Controller
Jul 18 23:53:50 RECALBOX user.info kernel: [  174.664565] usb 5-1: Manufacturer: ©Microsoft Corporation
Jul 18 23:53:50 RECALBOX user.info kernel: [  174.664572] usb 5-1: SerialNumber: 0EEA2B1
Jul 18 23:53:50 RECALBOX user.info kernel: [  174.706646] input: Microsoft X-Box 360 pad as /devices/platform/usb1/fe900000.dwc3/xhci-hcd.8.auto/usb5/5-1/5-1:1.0/input/input5
Jul 18 23:53:52 RECALBOX user.info kernel: [  176.215500] rockchip-vop ff900000.vop: [drm:vop_crtc_enable] Update mode to 1920x1080p60, type: 11

Plugging in sony and switch controllers work with no issues:

Jul 18 23:57:06 RECALBOX user.info kernel: [  370.579398] usb 8-1: USB disconnect, device number 3
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.404875] usb 8-1: new full-speed USB device number 4 using ohci-platform
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.706254] usb 8-1: New USB device found, idVendor=20d6, idProduct=a711
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.706265] usb 8-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.706271] usb 8-1: Product: Core (Plus) Wired Controller
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.706276] usb 8-1: Manufacturer: Bensussen Deutsch & Associates,Inc.(BDA)
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.706281] usb 8-1: SerialNumber: 000000000001
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.717235] input: Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller as /devices/platform/fe3a0000.usb/usb8/8-1/8-1:1.0/0003:20D6:A711.0002/input/input7
Jul 18 23:57:28 RECALBOX user.info kernel: [  392.769194] hid-generic 0003:20D6:A711.0002: input,hidraw0: USB HID v1.11 Gamepad [Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller] on usb-fe3a0000.usb-1/input0
Jul 18 23:57:42 RECALBOX user.info kernel: [  406.602681] usb 8-1: USB disconnect, device number 4
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.503938] usb 8-1: new full-speed USB device number 5 using ohci-platform
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.800193] usb 8-1: New USB device found, idVendor=054c, idProduct=05c4
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.800309] usb 8-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.800318] usb 8-1: Product: Wireless Controller
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.800325] usb 8-1: Manufacturer: Sony Computer Entertainment
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.806555] sony 0003:054C:05C4.0003: Using modified Dualshock 4 report descriptor with gyroscope axes
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.851454] input: Sony Computer Entertainment Wireless Controller as /devices/platform/fe3a0000.usb/usb8/8-1/8-1:1.0/0003:054C:05C4.0003/input/input8
Jul 18 23:57:57 RECALBOX user.info kernel: [  421.903280] sony 0003:054C:05C4.0003: input,hidraw0: USB HID v1.11 Gamepad [Sony Computer Entertainment Wireless Controller] on usb-fe3a0000.usb-1/input0




USB 2.0 vs 3.0 doesnt appear to effect it.

**Comment by eiddor** [comment]
Yep - Just tested a different one that is also Xbox style.  Same results.

**Comment by Nathan-j-hardee** [comment]
same results with an Xbox one controller.

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.

The issue described above should not exist on R-Cade. Game on!
