### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by IsaacDias2020** [mrfixit2001/recalbox-rockchip#11]
Hi, mrfixit2001.
I appreciate your efforts, but bluetooth connection is not working here in Rock Pi 4.
Your previous version of Recalbox, the bluetooth was ok.
Also the new version crashes randomly.
Greetings from Brazil.

**Comment by IsaacDias2020** [comment]
Bluetooth working here. My bad.

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.
