### ISSUE TITLE
wondering about recalbox 7

### ISSUE THREAD

**Issue by Ae3NerdGod** [mrfixit2001/recalbox-rockchip#12]
the ofc release is in 5 days, will an attempt be made to compile rb7 to rocck64? just wondering if there are plans, wanted to hear it from the horses mouth, no pressure.

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.
