### ISSUE TITLE
Kodi - PVR IPTV Simple not launching

### ISSUE THREAD

**Issue by nickustinov** [mrfixit2001/recalbox-rockchip#13]
Hi! Using latest image 200607, when in Kodi launching PVR IPTV Simple client shows "Unknown error" (same applies to all PVR addons). When enabling debugging here is what it shows:

```
2020-10-01 10:47:24.422 T:3967812560   ERROR: Unable to load /usr/lib/kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.4.8.4, reason: /usr/lib/kodi/addons/pvr.iptvsimple/pvr.iptvsimple.so.4.8.4: undefined symbol: IsTimeshifting
```

Any ideas? :)

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.

R-Cade has the latest version of Kodi and plugins, so I expect that should address the issue. But please do open a new issue on that GitHub if you encounter any problems. Thanks!!
