### ISSUE TITLE
HEVC 10-bit 1080p x265 Black Screen in Kodi

### ISSUE THREAD

**Issue by lwvmobile** [mrfixit2001/recalbox-rockchip#14]
Hello, just reporting that I'm getting black screen on playback of HEVC 10-bit 1080p (and presumably any other resolution) x265 files when attempting to playback with the DRM Prime hardware decoder. These files playback just fine in the LibreELEC Kodi implementation using the same HW decoder, so didn't know if it was a minor backend reason why it doesn't play back, or its more of a major issue.

**Comment by lwvmobile** [comment]
Oh, forgot to mention this is on the RK3328 chipset with Mali 450.

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.

R-Cade has the latest release of Kodi and performs better than any of my old recalbox releases did. Enjoy!
