### ISSUE TITLE
Source available?

### ISSUE THREAD

**Issue by wn2000** [mrfixit2001/recalbox-rockchip#15]
Hi @mrfixit2001 , great work and thanks for making this available!

I'm working on a system that uses the RK3328 chip. Right now I'm stuck with the stock firmware which is a buildroot based Linux. So I'm more interested in the user space emulators. Particularly how to get the best performance using those 3D based cores or standalone emulators, like N64/Dreamcast/Playstation/Saturn etc.

Down the road, it may be possible for someone to make a custom firmware, or even boot RecalBox directly for this system. So it'll be very helpful to learn what you've done on the system side as well.

Is the source for building these releases available? Any help on this is much appreciated.

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.

All the systems you're inquiring about are included in R-Cade :) Saturn's peformance isn't great yet, but it will improve in time. The others perform very well already.
