### ISSUE TITLE
ROCK64 PSP

### ISSUE THREAD

**Issue by b0b33140** [mrfixit2001/recalbox-rockchip#3]
Game : God Of War Ghost Of Sparta
The game is very slow

**Comment by mrfixit2001** [comment]
GOW is one of the most demanding PSP games - it's a lot to ask for the ROCK64 honestly. But it can still hit almost 100%fps with some config tweaks. Make a game-specific config, set the graphics to PSPx1, set the max fps to 30fps, and make sure frameskip is set to 3%.

**Comment by mrfixit2001** [comment]
Closing this - no response from user - my instructions above have been confirmed to allow the game to run at 90-100% fps
