### ISSUE TITLE
ROCK64 Dreamcast

### ISSUE THREAD

**Issue by b0b33140** [mrfixit2001/recalbox-rockchip#4]
Reicast
Many games have graphics bugs (Jet Grind Radio, Rival School 2 ...)
On my TV box SX905x2 the developer of Emuelec uses an old version of Reicast to solve this problem.

Flycast
The games work almost correctly at very low resolution. Is it possible to add support for the NAOMI and ATOMISWAVE in future versions?

**Comment by mrfixit2001** [comment]
Thanks for letting me know. It actually is a relatively older version of Reicast. The newer versions should improve the graphics compatibility, but flycast seems to be the best option moving forward. Will look for adding NAOMI and ATOMISWAVE.

**Comment by mrfixit2001** [comment]
Closing this - new release coming soon - I've changed dreamcast/atomiswave/naomi to run on flycast standalone and patched everything to work properly. Much better graphics and far fewer errors.
