### ISSUE TITLE
ROCK64 Scrapper

### ISSUE THREAD

**Issue by b0b33140** [mrfixit2001/recalbox-rockchip#5]
It is impossible to scrap games from recalbox

**Comment by mrfixit2001** [comment]
Thanks for letting me know. It's a pre-release because the recalbox devs haven't fixed all their bugs yet.

**Comment by eiddor** [comment]
Scraping still doesn't work for me on the RockPro64.

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.
