### ISSUE TITLE
 Crash when connecting a controller

### ISSUE THREAD

**Issue by b0b33140** [mrfixit2001/recalbox-rockchip#6]
When I plug in my wired xbox 360 controller, recalbox crashes.
recalbox-rock64-mrfixit-200607.img.xz

**Comment by mrfixit2001** [comment]
I have not seen this behavior, does it happen if you boot with them plugged in already?

>

**Comment by b0b33140** [comment]
Yes

**Comment by b0b33140** [comment]
Wireless xbox360 controllers work. When I connect the recalbox wired controllers freezes on a black recalbox screen or when I am in the menu.
![IMG_20200613_204822](https://user-images.githubusercontent.com/1975795/84576833-df962180-adb7-11ea-8b3c-f1c5cf8097fe.jpg)

**Comment by catbabylon** [comment]
I seem to be having exactly the same issue with a wired xbox 360 controller

**Comment by mo123** [comment]
Also crashes on the RockPi 4 when connecting or booting with any USB controller plugged into any of the 4 USB ports.

**Comment by jabreu-soap** [comment]
I have the same problem using the Retroflag Controller.

**Comment by mrfixit2001** [comment]
Wanted to let you all know that I don't plan on doing any more recalbox releases, as their development team was increasingly frustrating to try and work with. For now I would point any existing users over to batocera, as I've contributed much of my previous recalbox work into their releases. Additionally - I have a new project of my own launching very soon that is a partnership with Pine64 with releases specifically designed for rockchip and pine64 products. It will provide 99.9% of all the recalbox features and emulators, but add a bunch more with a ton of updates.

**Comment by eiddor** [comment]
Looking forward to that, @mrfixit2001 - I never got around to trying batocera after I saw your reply a few months ago.

**Comment by jabreu-soap** [comment]
Thank you @mrfixit2001!! I'll take a look on batocera, and looking foward to your next project!

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.
