### ISSUE TITLE
Cannot launch Naomi and Atomiswave games

### ISSUE THREAD

**Issue by b0b33140** [mrfixit2001/recalbox-rockchip#7]
Naomi and Atomiswave games are not displayed in the recalbox menu.
Cannot launch games directly from directly from the Reicast and Libretro Flycast emulators.
recalbox-rock64-mrfixit-200607.img.xz

**Comment by mrfixit2001** [comment]
These systems run fine, but they require you to first put their bios files in the correct locations 

>

**Comment by mrfixit2001** [comment]
If you are not seeing the roms show up in your list of games, then they do not have the right extensions or are the wrong file types. Please read the README file in the rom folder for each system to tell you what is supported.

>

**Comment by b0b33140** [comment]
Thank you, the extension was not the right one (bin) and I created the .lst file. Everything works.
