### ISSUE TITLE
which image to use

### ISSUE THREAD

**Issue by MX10-AC2N** [mrfixit2001/recalbox-rockchip#8]
Hi,
First I want to thank you for all this ..
I have a TV-Box made in china called MX10 ver1.0
https://www.geekbuying.com/item/MX10-Android-7-1-2-RK3328-4GB-32GB-TV-Box-388684.html
 and I wanted to know which image I can use on it ? Or otherwise what should I do as a modification in order to be able to use recalbox?
Thanks again..

**Comment by mrfixit2001** [comment]
That is hard to say without a technical spec sheet of the board you have. You might be able to get away with just be a different device tree. I would suggest trying the rock64 release.

>

**Comment by MX10-AC2N** [comment]
Thanks, This MX10 have :
CPU: RK3328 Quad-Core 64bit Cortex-A53
GPU: Penta-Core Mali-450
RAM: 4GB DDR4
ROM: EMMC 32GB
Wifi : RTL8723BS 2.4G WIFI, 802.11 b/g/n
LAN: 100M
No bluetooth
I will test Rock64 release but what do you means about "you might be able to get away with just be a different device tree" sorry but I'm a novice..
Thank again..

**Comment by MX10-AC2N** [comment]
Another question, if I see that everything is good, is it possible to install directly in the EMMC

**Comment by mrfixit2001** [comment]
By specs I mean the GPIO and regulator definitions. Put simply, device tree is part of the kernel and tells the software how to interact with the drivers for the hardware.
The image will boot from eMMC, yes, you’ll have to learn how to dd it to the proper mmcblk.  

>

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.
