### ISSUE TITLE
[Pinebook Pro] Glitched Screen On Startup

### ISSUE THREAD

**Issue by cow-killer** [mrfixit2001/recalbox-rockchip#9]
After flashing the Pinebook image to the SD card and turning the laptop on, the screen looks like this:
![distorted_recalbox_screen](https://user-images.githubusercontent.com/12868939/85086557-f1f1d000-b1a8-11ea-9c67-1fa724762662.jpg)
Audio is working fine though.

**Comment by mrfixit2001** [comment]
Wow - that's clearly not right. It doesn't happen on my pbp here - have you rebooted and reflashed?

**Comment by cow-killer** [comment]
Yes, tried different versions too. I noticed on the [Pine wiki](https://wiki.pine64.org/index.php/Pinebook_Pro_Software_Release#OS_Image_Releases) that "If Manjaro is installed on the eMMC you may experience issues booting different installations from SD card." I wonder if that's the issue since Manjoro KDE is installed by default.

**Comment by mrfixit2001** [comment]
I will no longer be updating any Recalbox releases. Instead I have developed an entirely new Retro-Gaming OS, [R-Cade,](https://www.retro-center.com/about-r-cade/) specifically optimized and designed for compatibility with Rockchip hardware provided by Pine64.

You can download the latest version of R-Cade for free here: https://github.com/retro-center/rcade_releases/releases

Feel free to check out the online store too!
[Retro Center - https://www.retro-center.com](https://www.retro-center.com)

Right now there are only RK3328 releases, but I'll be adding RK3399 in the future.
